apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: calibre
  namespace: argocd

spec: 
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: calibre
  project: default
  sources:
  - repoURL: https://k8s-at-home.com/charts/
    chart: calibre
    targetRevision: "*"
    helm:
      valueFiles:
        - $values/calibre/calibre_values.yml

  - repoURL: https://github.com/QDDragon/k3s-homelab.git
    targetRevision: main
    ref: values
    path: .
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


  