apiVersion: v1
kind: persistentVolumeClaim
metadata:
  name: calibre-books
  namespace: book
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
